#pragma once

typedef enum {
    MATRIX_OPERATION_OK = 0,
    MEMORY_ALLOCATION_FAILED = 100,
    MATRIX_NOT_DEFINED = 200,
    OPERATION_NOT_DEFINED = 201,
    WRONG_MATRIX_SIZE = 202,
    INCOMPATIBLE_MATRIX_TYPES = 300
} MatrixErrors;

